mutation createWithdrawalMethod($input: CreateOnlineWithdrawalMethodInput) {
  createOnlineAlipayWithdrawalMethod(input: $input)
}

###

mutation updateWithdrawalMethod($id: ID!, $input: UpdateOfflineBankTransferWithdrawalMethodInput) {
  updateOfflineBankTransferWithdrawalMethod(id: $id, input: $input)
}
