mutation createWithdrawalProvider($input: CreateWithdrawalProviderInput!) {
  createWithdrawalProvider(input: $input)
}

###
mutation deleteWithdrawalProvider($id: ID!) {
  deleteWithdrawalProvider(id: $id)
}